<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
<script>
    //gengretor函数是一个状态机，封装了多个内部状态；还是一个遍历器对象生成函数
    /*
    Generator 函数是一个普通函数，但是有两个特征。一是，function关键字与函数名之间有一个星号；
         二是，函数体内部使用yield表达式，定义不同的内部状态（yield在英语里的意思就是“产出”）
     */
    function* helloworldGenerator(){
        yield 'hello';
        yield 'world';
        return 'ending';
    }
    var hw = helloworldGenerator();
    hw.next();// { value: 'hello', done: false }
    hw.next();// { value: 'world', done: false }
    hw.next();// { value: 'ending, done: true }
    hw.next();// { value: undefined, done: true }

    //yield表达式，暂停执行函数

    function* foo() {
        yield 1;
        yield 2;
        yield 3;
        yield 4;
        yield 5;
        return 6;
    }

    for (let v of foo()) {
        console.log(v);
    }
    // 1 2 3 4 5

    //斐波那契数列    使用for...of语句时不需要使用next方法
    function* fibonacci() {
        let [prev, curr] = [0, 1];
        for (;;) {
            yield curr;
            [prev, curr] = [curr, prev + curr];
        }
    }

    for (let n of fibonacci()) {
        if (n > 1000) break;
        console.log(n);
    }


    //Generator.preototype.throw()  Generator 函数返回的遍历器对象，都有一个throw方法，可以在函数体外抛出错误，然后在 Generator 函数体内捕获
    var g = function* () {
        try {
            yield;
        } catch (e) {
            console.log('内部捕获', e);
        }
    };

    var i = g();
    i.next();

    try {
        i.throw('a');
        i.throw('b');
    } catch (e) {
        console.log('外部捕获', e);
    }
    // 内部捕获 a
    // 外部捕获 b

    var g = function* () {
        try {
            yield;
        } catch (e) {
            console.log(e);
        }
    };

    var i = g();
    i.next();
    i.throw(new Error('出错了！'));
    // Error: 出错了！(…)

    //Generator.prototype.return() 返回给定的值，并终结遍历generator函数
</script>
</html>